environment:
  matrix:
    - nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - curl -fsSL -o yarn.js https://github.com/yarnpkg/yarn/releases/download/v0.27.5/yarn-0.27.5.js
  - node ./yarn.js --version
  - node ./yarn.js install

cache:
  - node_modules

test_script:
  - node ./yarn.js run test -- --color

# Don't actually build.
build: off
